[project]
name = "sample_project"
version = "0.1.0"
description = "A sample Python project"

[build-system]
requires = ["setuptools >= 40.8.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["pysrc"]
