name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11' # Specify the Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest-cov flake8 radon # Install pytest-cov for coverage, flake8 for linting, and radon for cyclomatic complexity

    - name: Run unit tests
      run: |
        cd pysrc
        pytest tests --cov=. # Run tests with coverage

    - name: Lint with flake8
      run: |
        # Adjust flake8 command as needed. You can specify directories or files.
        flake8 pysrc --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 pysrc --count --exit-zero --max-complexity=3 --max-line-length=127 --statistics

    - name: Check cyclomatic complexity
      run: |
        # Use radon to check cyclomatic complexity
        radon cc pysrc -a -s

    - name: Check for test coverage
      run: |
        # Use pytest-cov to ensure a minimum coverage threshold, e.g., 80%
        cd pysrc
        pytest tests --cov=. --cov-fail-under=80
